# Generated by Django 4.1.6 on 2023-02-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
